server:
  port: 9980
  servlet:
    context path: "/google/v1"
spring:
  application.name: gemini
  mvc:
    path match:
      matching-strategy: ant-path-matcher

  data:
    mongodb:
      user: admin
      password: admin
      database: bus-booking-system
      uri: mongodb://localhost:27017

config:
  rest:
    service:
      google-gemini-url: https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent
    meta-data:
      key: AIzaSyBPBxmQqqyrodfSZJhiOzPvskmS4DyZIwc
